package OMS;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaztin Mojica
 */
public class YoloTeaUI extends javax.swing.JFrame {

    /**
     * Creates new form YoloTeaUI
     */
    private final SpecsDialog specs1 = new SpecsDialog();
    private final SpecsDialog specs2 = new SpecsDialog();
    private final SpecsDialog specs3 = new SpecsDialog();
    private final SpecsDialog specs4 = new SpecsDialog();
    private final SpecsDialog specs5 = new SpecsDialog();
    private final SpecsDialog specs6 = new SpecsDialog();
    private final SpecsDialog specs7 = new SpecsDialog();
    private final SpecsDialog specs8 = new SpecsDialog();
    private final SpecsDialog specs9 = new SpecsDialog();
    private final SpecsDialog specs10 = new SpecsDialog();
    private final SpecsDialog specs11 = new SpecsDialog();
    private final SpecsDialog specs12 = new SpecsDialog();
    private final SpecsDialog specs13 = new SpecsDialog();
    private final SpecsDialog specs14 = new SpecsDialog();
    private final SpecsDialog specs15 = new SpecsDialog();
    private final SpecsDialog specs16 = new SpecsDialog();
    private final SpecsDialog specs17 = new SpecsDialog();

    public YoloTeaUI() {
        initComponents();

        milkTeaTab.addTab("Yolavit",null, specs1.getContentPane(),null);
        milkTeaTab.addTab("Yolowinter",null, specs2.getContentPane(),null);
        milkTeaTab.addTab("YoloTaro",null, specs3.getContentPane(),null);
        milkTeaTab.addTab("Yolaberry",null, specs4.getContentPane(),null);
        milkTeaTab.addTab("Yolonilla",null, specs5.getContentPane(),null);
        milkTeaTab.addTab("Yolomatcha",null, specs6.getContentPane(),null);
        milkTeaTab.addTab("Carpe Diem",null, specs7.getContentPane(),null);
        milkTeaTab.addTab("WYSIWYG",null, specs8.getContentPane(),null);
        milkTeaTab.addTab("C'est la vie",null, specs9.getContentPane(),null);
        milkTeaTab.addTab("YoloChoco",null, specs10.getContentPane(),null);
        milkTeaTab.addTab("Jasmint",null, specs11.getContentPane(),null);
        milkTeaTab.addTab("YoloMocha",null, specs12.getContentPane(),null);
        milkTeaTab.addTab("YoloFoam",null, specs13.getContentPane(),null);
        milkTeaTab.addTab("YoloCaramel",null, specs14.getContentPane(),null);
        milkTeaTab.addTab("La Dolce Vita",null, specs15.getContentPane(),null);
        milkTeaTab.addTab("YoloKkaido",null, specs16.getContentPane(),null);
        milkTeaTab.addTab("YoloChocoNana",null, specs17.getContentPane(),null);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centerPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        upperLeftPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        userDetails = new javax.swing.JPanel();
        employeeNameLabel = new javax.swing.JLabel();
        employeeName = new javax.swing.JLabel();
        idNumberLabel = new javax.swing.JLabel();
        idNumber = new javax.swing.JLabel();
        selectionPanel = new javax.swing.JTabbedPane();
        milkTeaTab = new javax.swing.JTabbedPane();
        fruitTeaTab = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        hotTeaTab = new javax.swing.JTabbedPane();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        snacksTab = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        combosTab = new javax.swing.JTabbedPane();
        xlbw = new javax.swing.JPanel();
        xlnachos = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        orderPanel = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList();
        total = new javax.swing.JLabel();
        checkOutButton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.lightGray);
        setExtendedState(6);
        setUndecorated(true);

        java.awt.GridBagLayout centerPanelLayout = new java.awt.GridBagLayout();
        centerPanelLayout.columnWeights = new double[] {0.7, 0.3};
        centerPanelLayout.rowWeights = new double[] {1.0};
        centerPanel.setLayout(centerPanelLayout);

        leftPanel.setMinimumSize(new java.awt.Dimension(200, 110));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWeights = new double[] {1.0};
        jPanel1Layout.rowWeights = new double[] {0.1, 0.9};
        leftPanel.setLayout(jPanel1Layout);

        upperLeftPanel.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        java.awt.GridBagLayout upperLeftPanelLayout = new java.awt.GridBagLayout();
        upperLeftPanelLayout.columnWeights = new double[] {0.1, 0.6};
        upperLeftPanel.setLayout(upperLeftPanelLayout);

        logo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("Logo");
        logo.setMaximumSize(new java.awt.Dimension(123456789, 123456789));
        logo.setMinimumSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        upperLeftPanel.add(logo, gridBagConstraints);

        userDetails.setMaximumSize(new java.awt.Dimension(123456789, 123456789));
        userDetails.setMinimumSize(new java.awt.Dimension(20, 20));
        userDetails.setLayout(new java.awt.GridBagLayout());

        employeeNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        employeeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        employeeNameLabel.setText("EMPLOYEE NAME:");
        employeeNameLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        userDetails.add(employeeNameLabel, gridBagConstraints);

        employeeName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        employeeName.setText("Name");
        employeeName.setMinimumSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        userDetails.add(employeeName, gridBagConstraints);

        idNumberLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        idNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idNumberLabel.setText("I.D. No:");
        idNumberLabel.setMinimumSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        userDetails.add(idNumberLabel, gridBagConstraints);

        idNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        idNumber.setText("I.D. Number");
        idNumber.setMinimumSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        userDetails.add(idNumber, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        upperLeftPanel.add(userDetails, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        leftPanel.add(upperLeftPanel, gridBagConstraints);

        selectionPanel.setFont(new java.awt.Font("Helvetica Neue", 1, 32)); // NOI18N
        selectionPanel.setMinimumSize(new java.awt.Dimension(200, 60));

        milkTeaTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        milkTeaTab.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        selectionPanel.addTab("Milk Tea", milkTeaTab);

        fruitTeaTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        fruitTeaTab.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fruitTeaTab.addTab("YoloBlue", jPanel19);
        fruitTeaTab.addTab("YoloApple", jPanel20);
        fruitTeaTab.addTab("YoLychee", jPanel21);
        fruitTeaTab.addTab("Hakuna Matata", jPanel22);
        fruitTeaTab.addTab("Eureka", jPanel23);

        selectionPanel.addTab("Fruit Tea", fruitTeaTab);

        hotTeaTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        hotTeaTab.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        hotTeaTab.addTab("Assam/Jasmine", jPanel24);
        hotTeaTab.addTab("Stash Tea Bag", jPanel25);

        selectionPanel.addTab("Hot Tea", hotTeaTab);

        snacksTab.setMinimumSize(new java.awt.Dimension(20, 20));
        snacksTab.setLayout(new java.awt.GridLayout(9, 1));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton1.setText("Plain Belgian Waffle");
        snacksTab.add(jButton1);

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton2.setText("Caramel Belgian Waffle");
        snacksTab.add(jButton2);

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton3.setText("Chocolate Belgian Waffle");
        snacksTab.add(jButton3);

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton4.setText("Cheese Belgian Waffle");
        snacksTab.add(jButton4);

        jButton5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton5.setText("Nutella Belgian Waffle");
        snacksTab.add(jButton5);

        jButton6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton6.setText("Bananutella Belgian Waffle");
        snacksTab.add(jButton6);

        jButton7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton7.setText("Blueberry Cheese Belgian Waffle");
        snacksTab.add(jButton7);

        jButton8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton8.setText("Nachos");
        snacksTab.add(jButton8);

        jButton9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton9.setText("Extra Cheese");
        snacksTab.add(jButton9);

        selectionPanel.addTab("YoloSnacks", snacksTab);

        combosTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        combosTab.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        combosTab.addTab("XL + BW", xlbw);
        combosTab.addTab("XL + Nachos", xlnachos);

        selectionPanel.addTab("YoloCombos", combosTab);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        leftPanel.add(selectionPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        centerPanel.add(leftPanel, gridBagConstraints);

        rightPanel.setMinimumSize(new java.awt.Dimension(100, 110));
        rightPanel.setLayout(new java.awt.GridBagLayout());

        totalLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        totalLabel.setText("TOTAL:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        rightPanel.add(totalLabel, gridBagConstraints);

        orderList.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        orderList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        orderPanel.setViewportView(orderList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rightPanel.add(orderPanel, gridBagConstraints);

        total.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        total.setText("Php 0.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rightPanel.add(total, gridBagConstraints);

        checkOutButton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        checkOutButton.setText("CHECK OUT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        rightPanel.add(checkOutButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        centerPanel.add(rightPanel, gridBagConstraints);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Accounts");
        jMenu1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        menuBar.add(jMenu1);

        jMenu2.setText("Store");
        jMenu2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YoloTeaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new YoloTeaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JTabbedPane combosTab;
    private javax.swing.JLabel employeeName;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JTabbedPane fruitTeaTab;
    private javax.swing.JTabbedPane hotTeaTab;
    private javax.swing.JLabel idNumber;
    private javax.swing.JLabel idNumberLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane milkTeaTab;
    private javax.swing.JList orderList;
    private javax.swing.JScrollPane orderPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTabbedPane selectionPanel;
    private javax.swing.JPanel snacksTab;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JPanel upperLeftPanel;
    private javax.swing.JPanel userDetails;
    private javax.swing.JPanel xlbw;
    private javax.swing.JPanel xlnachos;
    // End of variables declaration//GEN-END:variables
}
